### ⚔️ 1. 점수 조정 (UC-B1)
POST http://localhost:8080/api/v1/judge/score/adjust
Content-Type: application/json

{
  "attackClubId": "b32a9c57-b16b-11f0-8541-b42e99d5ea15",
  "defenseClubId": "b32e36b6-b16b-11f0-8541-b42e99d5ea15",
  "delta": 1,
  "confirm": false
}

###

### ⛔ 2. 락 시간 내 재시도 (15분 이내)
POST http://localhost:8080/api/v1/judge/score/adjust
Content-Type: application/json

{
  "attackClubId": "b32a9c57-b16b-11f0-8541-b42e99d5ea15",
  "defenseClubId": "b32e36b6-b16b-11f0-8541-b42e99d5ea15",
  "delta": 1,
  "confirm": false
}

###

### ⚡ 3. 강제 조정 (락 무시 / confirm=true)
POST http://localhost:8080/api/v1/judge/score/adjust
Content-Type: application/json

{
  "attackClubId": "b32a9c57-b16b-11f0-8541-b42e99d5ea15",
  "defenseClubId": "b32e36b6-b16b-11f0-8541-b42e99d5ea15",
  "delta": -1,
  "confirm": true
}
###

###
GET http://localhost:8080/api/v1/judge/score/scoreboard?defenseClubName=눈꽃
Content-Type: application/json
###

###
POST http://localhost:8080/api/v1/judge/score/bonus
Content-Type: application/json

{
  "clubName": "우주탐구회",
  "delta": 11,
  "reason": "미션완료로 인해 보너스 획득"
}
###